## 异常
**异常处理方式是设计中应该重点考虑的问题。这样的程序才是最强壮的。Robust**  
### 异常类对象
程序产生异常时，JVM会自动实例化一个异常类的对象，对象中保存了具体的异常描述信息。　　　　

### try-catch-finally模型
        try{
            tryCode-尝试执行的代码块
        }
        catch(err){
            catchCode-捕获错误的代码块
        }
        finally{
            finallyCode-无论try/catch执行结果如何都会执行的代码
        }

#### try语句
try语句块后可以跟一个或者多个catch子句   
每个catch子句都有一个相关的异常类型   
出现异常时，流程将转到第一个与异常类匹配的子句中。  
#### finally子句
在catch子句后，可以跟一个*可选*的*finally*子句。    
finally子句中的语句总会被执行
***
### 多重错误处理
程序在开发中不会只存在一个异常，可能会同时存在多个异常时就需要使用**多个catch语句**进行处理。  

        public static void main(String[]args){
            int i,j;
            try{
                i=Integer.parseInt(args[0]);
                j=Integer.parseInt(args[2]);

                float temp=(float)i/(float)j;
                System.out.println("计算结果："+temp);

            }catch (ArithmeticException e){
                //System.out.println("算术异常\t");
                e.printStackTrace();
            }catch(NumberFormatException e){
                System.out.println("数字转换异常 "+e);
            }catch(ArrayIndexOutOfBoundsException e){
                System.out.println("数组越界异常");
                //使用Exception类提供的一个方法
                e.printStackTrace();
            }catch(Exception e){
                System.out.println("异常"+e);
            }
            finally {
                System.out.println("*************计算结束*************");
            }

## 异常信息的输出
* 直接打印异常对象 
<code>System.out.println(e)</code>       

* 使用Exception类提供的一个方法
<code>printStackTrace();</code>    
专门打印异常信息  

## 函数throw异常，调用该函数的做处理
        class MyException extends Throwable{
            private String info;
            MyException(String info){
                this.info=info;
            }
            public void printError(){
                System.out.println(info);
            }
        }
        public class Main{
            static void doRisky(String test)throws MyException{
                System.out.println("start risky");
                if("yes".equals(test))
                    throw  new MyException("bugs");
                System.out.println("end risky");
                return;
            }
            public static void main(String[] args) {
            try{
                System.out.println("start try");
                doRisky("yes");
                System.out.println("end try");
            }catch(MyException ex){
                System.out.println("scary Exception");
            }finally {
                System.out.println("finally");
            }
            }
        }
